const ActionTypes = {
    CHECK: 'CHECK',
    CHECKMATE: 'CHECKMATE',
    DRAW: 'DRAW',
    FIGURE_DELETED_WHITE: 'FIGURE_DELETED_WHITE',
    FIGURE_DELETED_BLACK: 'FIGURE_DELETED_BLACK',
    FIGURE_MOVING: 'FIGURE_MOVING',
    FIGURE_SELECT_START: 'FIGURE_SELECT_START',
    FIGURE_SELECT_END: 'FIGURE_SELECT_END',
    NEW_GAME: 'NEW_GAME',
    ROTATE_TABLE: 'ROTATE_TABLE',
    SELECT_FIELD: 'SELECT_FIELD'
};

export default ActionTypes;